pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                // Replace 'mvn clean install' with your actual build command
                sh 'mvn clean install'
            }
        }
        
        stage('Deploy') {
            steps {
                // Add deployment steps if needed
            }
        }
    }
}
